spring:
  security:
    oauth2:
      client:
        # provider:
        #   google: # override các thuộc tính mặc định của Google
        #     user-name-attribute: email # chỉ định Spring Security sẽ dùng field nào trong JSON của provider làm username
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}     
            scope:
              - openid
              - email
              - profile
  mail: # email của hệ thống (noreply email) dùng để gửi thư đi qua SMTP.
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD} #mật khẩu ứng dụng (apppasswords), với tên ứng dụng là: spring-security-abc-xyz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  recaptcha:
    secret: ${RECAPTCHA_SECRET}
  data:
    mongodb:
      uri: mongodb://localhost:27017/mtri-spring
mux:
  token-id: ${MUX_TOKEN_ID}
  token-secret: ${MUX_TOKEN_SECRET}
server:
  forward-headers-strategy: framework